home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

search:
    path:     /search
    defaults: { _controller: AppBundle:Search:search }

rent:
    path:     /rent
    defaults: { _controller: AppBundle:Default:index}

find_reservation:
    path:     /status
    defaults: { _controller: AppBundle:Default:index}

show_reservation:
    path:     /status/{id}
    defaults: { _controller: AppBundle:Default:index}


